"""init

Revision ID: 434d5a9445cb
Revises: 
Create Date: 2026-01-16 15:35:08.713783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
# import app


# revision identifiers, used by Alembic.
revision: str = '434d5a9445cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('google_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'CHANGED', 'CANCELLED', 'COMPLETED', 'MISSED', name='eventstatus'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_google_event_id'), 'events', ['google_event_id'], unique=True)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_summary'), 'events', ['summary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_summary'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_google_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
